from django.utils import timezone
from mongoengine import fields, Document


class Evaluation (Document):
    evaluation_date = fields.DateTimeField(
        default=timezone.now, verbose_name='eval date')
    name = fields.StringField()
    age = fields.IntField()
    gender = fields.StringField(max_length=1)
    wheight = fields.FloatField()
    height = fields.FloatField()
    amputationCause = fields.StringField(max_length=25)
    amputationTime = fields.IntField()
    amputationType = fields.BooleanField()
    symptoms = fields.StringField(max_length=50)
    medications = fields.StringField()
    fisioTreatment = fields.BooleanField()
    pregressLife = fields.StringField()
    skinCondition = fields.StringField(max_length=50)
    skinTemperature = fields.BooleanField()
    skinHairandNails = fields.BooleanField()
    skinColor = fields.StringField()
    skinSensibility = fields.StringField(max_length=50)
    skinConditions = fields.StringField(max_length=50)
    skinPulses = fields.StringField()
    deformities = fields.StringField()
    trofism = fields.StringField()
    bandaging = fields.BooleanField()
    movementAmplitudeFlexion = fields.IntField()
    movementAmplitudeAbdution = fields.IntField()
    movementAmplitudeAddution = fields.IntField()
    musculePowerFlexion = fields.IntField()
    musculePowerAbdution = fields.IntField()
    musculePowerAddution = fields.IntField()
    stumpLength = fields.FloatField()
    stumpCircumference = fields.FloatField()
    legLength = fields.FloatField()
    legCircunference = fields.FloatField()
    posturalEvaluation = fields.StringField()
