# Generated by Django 2.0 on 2017-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('wheight', models.FloatField()),
                ('height', models.FloatField()),
                ('amputationCause', models.CharField(max_length=25)),
                ('amputationTime', models.IntegerField()),
                ('amputationType', models.BooleanField()),
                ('symptoms', models.CharField(max_length=50)),
                ('medications', models.TextField()),
                ('fisioTreatment', models.BooleanField()),
                ('pregressLife', models.TextField()),
                ('skinCondition', models.CharField(max_length=50)),
                ('skinTemperature', models.BooleanField()),
                ('skinHairandNails', models.BooleanField()),
                ('skinColor', models.TextField()),
                ('skinSensibility', models.CharField(max_length=50)),
                ('skinConditions', models.CharField(max_length=50)),
                ('skinPulses', models.TextField()),
                ('deformities', models.TextField()),
                ('trofism', models.TextField()),
                ('bandaging', models.BooleanField()),
                ('movementAmplitudeFlexion', models.IntegerField()),
                ('movementAmplitudeAbdution', models.IntegerField()),
                ('movementAmplitudeAddution', models.IntegerField()),
                ('musculePowerFlexion', models.IntegerField()),
                ('musculePowerAbdution', models.IntegerField()),
                ('musculePowerAddution', models.IntegerField()),
                ('stumpLength', models.FloatField()),
                ('stumpCircumference', models.FloatField()),
                ('legLength', models.FloatField()),
                ('legCircunference', models.FloatField()),
                ('posturalEvaluation', models.TextField()),
            ],
        ),
    ]
