from django.db import models


class Evaluation (models.Model):
    nome = models.CharField(max_length=50)
    idade = models.IntegerField()
    sexo = models.CharField(max_length=1)
    peso = models.FloatField()
    altura = models.FloatField()
    causaAmputacao = models.CharField(max_length=25)
    tempoAmputacao = models.IntegerField()
    tipoAmputacao = models.BooleanField()
    sintomas = models.CharField(max_length=50)
    medicacoes = models.TextField()
    tratamentoFisioterapeuticoAnterior = models.BooleanField()
    historicoPregresso = models.TextField()
    condicaoDaPele = models.CharField(max_length=50)
    temperaturaAlterada = models.BooleanField()
    alteracaoDeUnhaEPelos = models.BooleanField()
    alteracaoDeCorDaPele = models.TextField()
    sentibilidadeNaPele = models.CharField(max_length=50)
    condicaoDaPele = models.CharField(max_length=50)
    pulsosNaPele = models.TextField()
    deformidades = models.TextField()
    trofismo = models.TextField()
    enfaixamento = models.BooleanField()
    amplitudeDeMovimentoFlexao = models.IntegerField()
    movementAmplitudeAbdution = models.IntegerField()
    movementAmplitudeAddution = models.IntegerField()
    musculePowerFlexion = models.IntegerField()
    musculePowerAbdution = models.IntegerField()
    musculePowerAddution = models.IntegerField()
    stumpLength = models.FloatField()
    stumpCircumference = models.FloatField()
    legLength = models.FloatField()
    legCircunference = models.FloatField()
    posturalEvaluation = models.TextField()
